# Generated by Django 4.1.7 on 2023-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered_at",
            field=models.DateField(null=True),
        ),
    ]
