# Generated by Django 4.1.7 on 2023-02-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_ordered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
